name: wf-develop-pr
on:
  pull_request:
    branches:
      - develop 
jobs:
  linting-job:
    name: Lint HTML and CSS Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Lint HTML and CSS
        run: |
          npx htmlhint "**/*.html" || echo "No HTML files to lint yet."
          npx stylelint "**/*.css" || echo "No CSS files to lint yet."
  build-pr:
    name: Build the Website
    runs-on: ubuntu-latest
    needs: linting-job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build Website
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./" || echo "No files to build yet"